language: objective-c

before_install:
    - gem update cocoapods --quiet
    - pod --version

script:
    - xctool -workspace Examples.xcworkspace -scheme StoryBoard1 -sdk iphonesimulator build
    - xctool -workspace Examples.xcworkspace -scheme CmdBar1 -sdk iphonesimulator build
    - xctool -workspace Examples.xcworkspace -scheme OptionsView1 -sdk iphonesimulator build
